version: '3'

services:
  app:
    container_name: honest-journal-node
    restart: always
    build: .
    ports:
      - '80:3000'
    external_links:
      - mongo
  mongo:
    container_name: honest-journal-mongo
    image: mongo
    ports:
      - '27017:27017'